#!/bin/bash
# Remove auto-generated API documentation files from git tracking
# Run this once to clean up your repository

set -e

echo "=========================================="
echo "Cleaning up tracked API documentation"
echo "=========================================="
echo ""

cd "$(dirname "$0")/.."

echo "Current status:"
git status --short docs/api/

echo ""
echo "Removing tracked auto-generated files..."

# Remove files matching our auto-generated patterns
git rm --cached docs/api/pygeon*.rst 2>/dev/null || true
git rm --cached docs/api/*_h1.rst 2>/dev/null || true
git rm --cached docs/api/*_hdiv.rst 2>/dev/null || true
git rm --cached docs/api/*_hcurl.rst 2>/dev/null || true
git rm --cached docs/api/*_l2.rst 2>/dev/null || true
git rm --cached docs/api/*_vec*.rst 2>/dev/null || true
git rm --cached docs/api/discretizations_*.rst 2>/dev/null || true
git rm --cached docs/api/vem_*.rst 2>/dev/null || true
git rm --cached docs/api/fem_*.rst 2>/dev/null || true

echo ""
echo "✓ Files removed from git tracking (but kept locally)"
echo ""
echo "Next steps:"
echo "1. Review the changes: git status"
echo "2. Commit the change: git commit -m 'Stop tracking auto-generated API docs'"
echo "3. Push to GitHub: git push"
echo ""
echo "After this, generated API files will:"
echo "  • Still exist locally after 'make html'"
echo "  • NOT be committed to git"
echo "  • Be auto-generated by ReadTheDocs"
