# Adapted from PorePy
# Run unit, integration, and functional tests.
name: Pytest

# Controls when the action will run. Triggers the workflow on push or pull request
# events for the main and develop branches
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Do a nightly run of the tests
    - cron: '0 1 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Pytest
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#specifying-a-python-version
    strategy:
      matrix:
        python-version:  ["3.12", "3.13"]
      # Complete all versions in matrix even if one fails.
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Setup Python ${{ matrix.python-version}}
      uses: actions/setup-python@v5
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: ${{ matrix.python-version}}
        architecture: x64
        cache: 'pip'

    # Cache pip dependencies
    # Source: https://github.com/actions/cache/blob/main/examples.md#python---pip
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        # Cache the full python environment, this is more efficient than just caching pip
        # https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

    - name: Install external libraries
      run: |
        # Various packages that must be installed
        sudo apt-get install libglu1-mesa libgeos-dev libffi-dev
        export LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH

    - name: Install requirements and PyGeoN
      run: |
        pip install -U pip
        # Install requirements, using eager updates to avoid stalled dependencies due to caching
        # https://blog.allenai.org/python-caching-in-github-actions-e9452698e98d
        pip install --upgrade --upgrade-strategy eager --force-reinstall -e .
        pip freeze

    - name: unit tests
      if: ${{always()}}
      run: pytest tests/unit

    - name: integration tests
      if: ${{always()}}
      run: pytest tests/integration
